---

- hosts: all
  become: true
  tasks:

  - name: copy html file for site
    tags: apache,apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /temp/index.html
      owner: root
      group: root
      mode: 0644
    when: ansible_distribution == "SLES"

  - name: copy html file for site
    tags: apache,apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /temp/index.html
      owner: root
      group: root
      mode: 0644
    when: ansible_distribution == "Ubuntu"


