---

- hosts: all
  become: true
  tasks:

  - name: install updates (ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
    tags: [update,upgrade]

- hosts: all
  become: true
  tasks:

  - name: install apache2 package
    apt:
      name: apache2
    tags: [apache,apache2,server]

  - name: install vim package
    apt:
      name: vim
    tags: [vim,text,editor]


  - name: copy html file for site
    tags: apache,apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
