---

- hosts: all
  become: true
  tasks:

  - name: install updates (ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
    tags: [update,upgrade]

  # - name: install terraform
  # unarchive:
  # src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
  #   dest: /usr/local/bin
  #   remote_src: yes
  #   mode: 0755
  #   owner: root
  #   group: root

- hosts: all
  become: true
  tasks:

  - name: install apache2 package
    apt:
      name: apache2
    tags: [apache,apache2,server]
    when: ansible_distribution = "Ubuntu"

  - name: install vim package
    apt:
      name: vim
    tags: [vim,text,editor]
    when: ansible_distribution = "Ubuntu"

  - name: install vim package
    zypper:
      name: vim
    tags: sles,vim
    when: ansible_distribution = "SLES"    

  - name: copy html file for site
    tags: apache,apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
