---

- hosts: all
  become: true
  tasks:
  
  - name: install apache2 package
    apt: 
      name: apache2
      state: absent

  - name: install vim package
    apt:
      name: vim
      state: absent
