---

- hosts: all
  become: true
  tasks:

  - name: install httpd package in (SLES)
    tags: apache,SLES,apache2
    zypper:
      name:
        - apache2
        - php
      state: latest
    when: ansible_distribution == "SLES"

  - name: start and enable httpd (SLES)
    tags: apache,centos,apache2
    service:
      name: apache2
      state: started
      enabled: yes
    when: ansible_distribution == "SLES"

  - name: install apache2 package in (Ubuntu)
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: start and enable httpd (Ubuntu)
    tags: apache,Ubuntu,apache2
    service:
      name: apache2
      state: started
    when: ansible_distribution == "Ubuntu"
